'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class HadiwarningIntervalsEdit
    
    '''<summary>
    '''Bootstrap_Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Bootstrap_Panel1 As Global.MehrVosul.Bootstrap_Panel
    
    '''<summary>
    '''lblInnerPageTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInnerPageTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtWarningIntervalsName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWarningIntervalsName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''divDeposit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDeposit As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divchklstDepositItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divchklstDepositItems As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divLoan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divLoan As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divchklstLoanTypeItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divchklstLoanTypeItems As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divTree control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTree As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''treeViewDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents treeViewDiv As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''trState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trState As Global.System.Web.UI.WebControls.TreeView
    
    '''<summary>
    '''txtFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFrom As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cmbFrequencyInDay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbFrequencyInDay As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''StartTimePicker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StartTimePicker As Global.MehrVosul.UC_TimePicker
    
    '''<summary>
    '''cmbFrequencyInHour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbFrequencyInHour As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''chkbxSendSMS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkbxSendSMS As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''chkbxCallTelephone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkbxCallTelephone As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''chkbxVoiceMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkbxVoiceMessage As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''rdoNewDeposit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdoNewDeposit As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''rdoGetDeposit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdoGetDeposit As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''chkStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkStatus As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''divBranches control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divBranches As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''hdnAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnAction As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnWarningIntervalTypeNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnWarningIntervalTypeNew As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnWarningIntervalTypeEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnWarningIntervalTypeEdit As Global.System.Web.UI.WebControls.HiddenField
End Class
