'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_HadiWarningIntervals
    Public Property ID As Integer
    Public Property FromDay As Nullable(Of Integer)
    Public Property ToDay As Nullable(Of Integer)
    Public Property WarniningTitle As String
    Public Property FrequencyInDay As Nullable(Of Integer)
    Public Property StartTime As Nullable(Of System.TimeSpan)
    Public Property FrequencyPeriodHour As Nullable(Of Integer)
    Public Property SendSMS As Nullable(Of Boolean)
    Public Property CallTelephone As Nullable(Of Boolean)
    Public Property VoiceMessage As Nullable(Of Boolean)
    Public Property ForDeposit As Nullable(Of Boolean)
    Public Property FK_CUserID As Nullable(Of Integer)
    Public Property FK_EUserID As Nullable(Of Integer)
    Public Property CTime As Nullable(Of Date)
    Public Property ETime As Nullable(Of Date)
    Public Property IsActive As Nullable(Of Boolean)

    Public Overridable Property tbl_HadiDraftText As ICollection(Of tbl_HadiDraftText) = New HashSet(Of tbl_HadiDraftText)
    Public Overridable Property tbl_HadiWarningIntervalsBranch As ICollection(Of tbl_HadiWarningIntervalsBranch) = New HashSet(Of tbl_HadiWarningIntervalsBranch)
    Public Overridable Property tbl_HadiWarningIntervalsDeposit As ICollection(Of tbl_HadiWarningIntervalsDeposit) = New HashSet(Of tbl_HadiWarningIntervalsDeposit)
    Public Overridable Property tbl_HadiWarningNotificationLog As ICollection(Of tbl_HadiWarningNotificationLog) = New HashSet(Of tbl_HadiWarningNotificationLog)
    Public Overridable Property tbl_HadiWarningIntervalsException As ICollection(Of tbl_HadiWarningIntervalsException) = New HashSet(Of tbl_HadiWarningIntervalsException)
    Public Overridable Property tbl_HadiWarningIntervalsLoan As ICollection(Of tbl_HadiWarningIntervalsLoan) = New HashSet(Of tbl_HadiWarningIntervalsLoan)

End Class
