'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_HadiWarningNotificationLog
    Public Property ID As Integer
    Public Property FK_FileID As Nullable(Of Integer)
    Public Property FK_HadiWarningIntervalID As Nullable(Of Integer)
    Public Property theDay As Nullable(Of Date)
    Public Property FrquencyNo As Nullable(Of Integer)
    Public Property STime As Nullable(Of Date)
    Public Property IsHandy As Nullable(Of Boolean)

    Public Overridable Property tbl_HadiWarningIntervals As tbl_HadiWarningIntervals
    Public Overridable Property tbl_File As tbl_File
    Public Overridable Property tbl_HadiWarningNotificationLogDetail As ICollection(Of tbl_HadiWarningNotificationLogDetail) = New HashSet(Of tbl_HadiWarningNotificationLogDetail)

End Class
