'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_User
    Public Property ID As Integer
    Public Property Username As String
    Public Property Password As String
    Public Property IsActive As Nullable(Of Boolean)
    Public Property IsDataAdmin As Nullable(Of Boolean)
    Public Property IsItemAdmin As Nullable(Of Boolean)
    Public Property IsDataUserAdmin As Nullable(Of Boolean)
    Public Property FName As String
    Public Property LName As String
    Public Property Email As String
    Public Property Sex As Nullable(Of Boolean)
    Public Property Tel As String
    Public Property Mobile As String
    Public Property STime As Nullable(Of Date)
    Public Property FK_UserID As Nullable(Of Integer)
    Public Property PersonCode As String
    Public Property NationalID As String
    Public Property NationalNo As String
    Public Property Address As String
    Public Property UserPhoto As Byte()
    Public Property FK_BrnachID As Nullable(Of Integer)
    Public Property IsPartTime As Nullable(Of Boolean)

    Public Overridable Property tbl_Accessgroup As ICollection(Of tbl_Accessgroup) = New HashSet(Of tbl_Accessgroup)
    Public Overridable Property tbl_AccessgroupUser As ICollection(Of tbl_AccessgroupUser) = New HashSet(Of tbl_AccessgroupUser)
    Public Overridable Property tbl_File As ICollection(Of tbl_File) = New HashSet(Of tbl_File)
    Public Overridable Property tbl_File1 As ICollection(Of tbl_File) = New HashSet(Of tbl_File)
    Public Overridable Property tbl_File2 As ICollection(Of tbl_File) = New HashSet(Of tbl_File)
    Public Overridable Property tbl_SystemLoginLog As ICollection(Of tbl_SystemLoginLog) = New HashSet(Of tbl_SystemLoginLog)
    Public Overridable Property tbl_Branch As tbl_Branch

End Class
