'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_WarningNotificationLog
    Public Property ID As Integer
    Public Property FK_LoanID As Nullable(Of Integer)
    Public Property FK_FileID As Nullable(Of Integer)
    Public Property FK_WarningIntervalID As Nullable(Of Integer)
    Public Property theDay As Nullable(Of Date)
    Public Property FrquencyNo As Nullable(Of Integer)
    Public Property STime As Nullable(Of Date)
    Public Property IsHandy As Nullable(Of Boolean)

    Public Overridable Property tbl_File As tbl_File
    Public Overridable Property tbl_Loan As tbl_Loan
    Public Overridable Property tbl_WarningIntervals As tbl_WarningIntervals
    Public Overridable Property tbl_WarningNotificationLogDetail As ICollection(Of tbl_WarningNotificationLogDetail) = New HashSet(Of tbl_WarningNotificationLogDetail)

End Class
