'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_AlcatelLog
    Public Property ID As Integer
    Public Property STime As Nullable(Of Date)
    Public Property TelMobile As String
    Public Property LoanNumber As String
    Public Property NPDuration As Nullable(Of Integer)
    Public Property Success As Nullable(Of Boolean)
    Public Property Remarks As String
    Public Property CallDuration As String
    Public Property Repeat As Nullable(Of Integer)
    Public Property T1 As Nullable(Of Boolean)

End Class
