'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_Deposits
    Public Property ID As Integer
    Public Property FK_FileID As Nullable(Of Integer)
    Public Property FK_DepositTypeID As Nullable(Of Integer)
    Public Property DepositAmount As Nullable(Of Double)
    Public Property FK_BranchID As Nullable(Of Integer)
    Public Property DepositNumber As String
    Public Property DepositOpenDate As Nullable(Of Date)
    Public Property STime As Nullable(Of Date)

    Public Overridable Property tbl_Branch As tbl_Branch
    Public Overridable Property tbl_DepositType As tbl_DepositType
    Public Overridable Property tbl_File As tbl_File
    Public Overridable Property tbl_HadiOperation_Deposit As ICollection(Of tbl_HadiOperation_Deposit) = New HashSet(Of tbl_HadiOperation_Deposit)

End Class
