'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_Date
    Public Property ID As Integer
    Public Property DateG As Nullable(Of Date)
    Public Property Year As Nullable(Of Integer)
    Public Property Month As Nullable(Of Byte)
    Public Property Day As Nullable(Of Byte)
    Public Property YearP As Nullable(Of Integer)
    Public Property MonthP As Byte
    Public Property DayP As Nullable(Of Byte)
    Public Property DateP As String
    Public Property WeekName As String
    Public Property WeekNameP As String
    Public Property MonthName As String
    Public Property MonthNameP As String
    Public Property WeekNo As Nullable(Of Byte)
    Public Property [Date] As String
    Public Property WeekDayNo As String
    Public Property WeekDayNoID As Integer
    Public Property YearMonthP As Nullable(Of Integer)

End Class
