'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_PreWarningNotificationLog
    Public Property ID As Integer
    Public Property FK_LoanID As Nullable(Of Integer)
    Public Property FK_FileID As Nullable(Of Integer)
    Public Property FK_PreWarningIntervalID As Nullable(Of Integer)
    Public Property theDay As Nullable(Of Date)
    Public Property STime As Nullable(Of Date)
    Public Property IsHandy As Nullable(Of Boolean)

    Public Overridable Property tbl_PreWarningNotificationLog1 As ICollection(Of tbl_PreWarningNotificationLog) = New HashSet(Of tbl_PreWarningNotificationLog)
    Public Overridable Property tbl_PreWarningNotificationLog2 As tbl_PreWarningNotificationLog

End Class
