'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_WarningIntervals
    Public Property ID As Integer
    Public Property FromDay As Nullable(Of Integer)
    Public Property ToDay As Nullable(Of Integer)
    Public Property WarniningTitle As String
    Public Property FrequencyInDay As Nullable(Of Integer)
    Public Property StartTime As Nullable(Of System.TimeSpan)
    Public Property FrequencyPeriodHour As Nullable(Of Integer)
    Public Property SendSMS As Nullable(Of Boolean)
    Public Property CallTelephone As Nullable(Of Boolean)
    Public Property IssueIntroductionLetter As Nullable(Of Boolean)
    Public Property IssueNotice As Nullable(Of Boolean)
    Public Property IssueManifest As Nullable(Of Boolean)
    Public Property VoiceMessage As Nullable(Of Boolean)
    Public Property ToBorrower As Nullable(Of Boolean)
    Public Property ToSponsor As Nullable(Of Boolean)
    Public Property FK_CUserID As Nullable(Of Integer)
    Public Property FK_EUserID As Nullable(Of Integer)
    Public Property CTime As Nullable(Of Date)
    Public Property ETime As Nullable(Of Date)
    Public Property MinimumAmount As Nullable(Of Decimal)
    Public Property LoanAmount As Nullable(Of Decimal)
    Public Property InstalmentAmount As Nullable(Of Decimal)
    Public Property ISActive As Nullable(Of Boolean)

    Public Overridable Property tbl_DraftText As ICollection(Of tbl_DraftText) = New HashSet(Of tbl_DraftText)
    Public Overridable Property tbl_WarningIntervalsLoanType As ICollection(Of tbl_WarningIntervalsLoanType) = New HashSet(Of tbl_WarningIntervalsLoanType)
    Public Overridable Property tbl_WarningIntervalsException As ICollection(Of tbl_WarningIntervalsException) = New HashSet(Of tbl_WarningIntervalsException)
    Public Overridable Property tbl_WarningNotificationLog As ICollection(Of tbl_WarningNotificationLog) = New HashSet(Of tbl_WarningNotificationLog)

End Class
