'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_HadiOperation_Loan
    Public Property ID As Integer
    Public Property LCAamountPaid As Nullable(Of Decimal)
    Public Property AmountDefferd As Nullable(Of Decimal)
    Public Property Status As String
    Public Property FK_FileID As Nullable(Of Integer)
    Public Property FK_LoanTypeID As Nullable(Of Integer)
    Public Property Process As Nullable(Of Boolean)
    Public Property FK_BranchID As Nullable(Of Integer)
    Public Property LCDate As Nullable(Of Date)
    Public Property FK_LoanID As Nullable(Of Integer)

    Public Overridable Property tbl_Branch As tbl_Branch
    Public Overridable Property tbl_File As tbl_File
    Public Overridable Property tbl_Loan As tbl_Loan
    Public Overridable Property tbl_LoanType As tbl_LoanType

End Class
