'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_Sponsors_List
    Public Property ID As Integer
    Public Property BranchCode As String
    Public Property LoanTypeCode As String
    Public Property BorrowerCustomerNo As String
    Public Property LoanSerial As Nullable(Of Integer)
    Public Property SponsorCustomerNo As String
    Public Property FullName As String
    Public Property FatherName As String
    Public Property MobileNo As String
    Public Property NationalID As String
    Public Property IDNumber As String
    Public Property Address As String
    Public Property TelephoneHome As String
    Public Property TelephoneWork As String
    Public Property WarantyTypeDesc As String

End Class
