'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_TotalDeffredLC
    Public Property ID As Integer
    Public Property Date_P As Nullable(Of Date)
    Public Property AmounDefferd As Nullable(Of Decimal)
    Public Property Status As String
    Public Property NotPiadDurationDay As Nullable(Of Integer)
    Public Property NoDelayInstallment As Nullable(Of Integer)
    Public Property CustomerNO As String
    Public Property LCNumber As String
    Public Property BranchCode As String
    Public Property FullName As String
    Public Property MobileNO As String
    Public Property LoanTypeCode As String
    Public Property LoanType As String
    Public Property Process As Nullable(Of Boolean)

End Class
