'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_HadiOperation_Deposit
    Public Property ID As Integer
    Public Property Date_p As Nullable(Of Date)
    Public Property FK_FileID As Nullable(Of Integer)
    Public Property CFCRDate As Nullable(Of Date)
    Public Property FK_BranchID As Nullable(Of Integer)
    Public Property DepositNO As String
    Public Property FK_DepositTypeID As Nullable(Of Integer)
    Public Property FK_DepositID As Nullable(Of Integer)
    Public Property Process As Nullable(Of Boolean)

    Public Overridable Property tbl_Deposits As tbl_Deposits
    Public Overridable Property tbl_DepositType As tbl_DepositType

End Class
