'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_WarnatyType
    Public Property ID As Integer
    Public Property Decp As String

    Public Overridable Property tbl_LoanSponsor_WarantyType As ICollection(Of tbl_LoanSponsor_WarantyType) = New HashSet(Of tbl_LoanSponsor_WarantyType)

End Class
