'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_PreWarningIntervals
    Public Property ID As Integer
    Public Property onDay As Nullable(Of Integer)
    Public Property WarniningTitle As String
    Public Property SendSMS As Nullable(Of Boolean)
    Public Property VoiceMessage As Nullable(Of Boolean)
    Public Property FK_CUserID As Nullable(Of Integer)
    Public Property FK_EUserID As Nullable(Of Integer)
    Public Property CTime As Nullable(Of Date)
    Public Property ETime As Nullable(Of Date)
    Public Property MinimumAmount As Nullable(Of Decimal)
    Public Property LoanAmount As Nullable(Of Decimal)
    Public Property InstalmentAmount As Nullable(Of Decimal)
    Public Property IsActive As Nullable(Of Boolean)

    Public Overridable Property tbl_PreWarningIntervalsBranch As ICollection(Of tbl_PreWarningIntervalsBranch) = New HashSet(Of tbl_PreWarningIntervalsBranch)
    Public Overridable Property tbl_PreWarningIntervalsLoanType As ICollection(Of tbl_PreWarningIntervalsLoanType) = New HashSet(Of tbl_PreWarningIntervalsLoanType)

End Class
