'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_Menu
    Public Property ID As Integer
    Public Property MenuTitle As String
    Public Property OrderIn As Nullable(Of Integer)
    Public Property FK_SiblingID As Nullable(Of Integer)
    Public Property FK_ParentID As Nullable(Of Integer)
    Public Property URL As String
    Public Property IsVisible As Nullable(Of Boolean)
    Public Property ClassName As String
    Public Property PageTitle As String
    Public Property IconText As String
    Public Property IconSize As Nullable(Of Integer)
    Public Property IsLeaf As Nullable(Of Boolean)

    Public Overridable Property tbl_AccessgroupMenu As ICollection(Of tbl_AccessgroupMenu) = New HashSet(Of tbl_AccessgroupMenu)

End Class
