'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_ErrorLog
    Public Property ID As Integer
    Public Property ErrorMessage As String
    Public Property ErrorType As Nullable(Of Byte)
    Public Property STime As Nullable(Of Date)
    Public Property ErrorName As String

End Class
