'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_HadiWarningIntervalsExceptionBranch
    Public Property ID As Integer
    Public Property FK_HadiWarningIntervalsExceptionID As Nullable(Of Integer)
    Public Property FK_HadiWarningIntervalBranchID As Nullable(Of Integer)

    Public Overridable Property tbl_HadiWarningIntervalsBranch As tbl_HadiWarningIntervalsBranch
    Public Overridable Property tbl_HadiWarningIntervalsException As tbl_HadiWarningIntervalsException

End Class
