'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_HadiWarningIntervalsException
    Public Property ID As Integer
    Public Property FK_HadiWarningIntervalID As Nullable(Of Integer)
    Public Property ExceptionName As String
    Public Property ISActive As Nullable(Of Boolean)

    Public Overridable Property tbl_HadiWarningIntervals As tbl_HadiWarningIntervals
    Public Overridable Property tbl_HadiWarningIntervalsExceptionBranch As ICollection(Of tbl_HadiWarningIntervalsExceptionBranch) = New HashSet(Of tbl_HadiWarningIntervalsExceptionBranch)

End Class
