'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_WarningIntervalsLoanType
    Public Property ID As Integer
    Public Property FK_WarningIntervalID As Nullable(Of Integer)
    Public Property FK_LoanTypeID As Nullable(Of Integer)

    Public Overridable Property tbl_LoanType As tbl_LoanType
    Public Overridable Property tbl_WarningIntervals As tbl_WarningIntervals
    Public Overridable Property tbl_WarningIntervalsExceptionLoanType As ICollection(Of tbl_WarningIntervalsExceptionLoanType) = New HashSet(Of tbl_WarningIntervalsExceptionLoanType)

End Class
