'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_File
    Public Property ID As Integer
    Public Property CustomerNo As String
    Public Property FName As String
    Public Property LName As String
    Public Property FatherName As String
    Public Property MobileNo As String
    Public Property NationalID As String
    Public Property IDNumber As String
    Public Property Email As String
    Public Property Address As String
    Public Property TelephoneHome As String
    Public Property TelephoneWork As String
    Public Property IsMale As Nullable(Of Boolean)
    Public Property CTime As Nullable(Of Date)
    Public Property FK_CUserID As Nullable(Of Integer)
    Public Property ETime As Nullable(Of Date)
    Public Property FK_EUserID As Nullable(Of Integer)
    Public Property State As Nullable(Of Byte)
    Public Property FK_OriginalFileID As Nullable(Of Integer)
    Public Property FK_RequestUserID As Nullable(Of Integer)

    Public Overridable Property tbl_User As tbl_User
    Public Overridable Property tbl_User1 As tbl_User
    Public Overridable Property tbl_User2 As tbl_User
    Public Overridable Property tbl_HadiWarningNotificationLog As ICollection(Of tbl_HadiWarningNotificationLog) = New HashSet(Of tbl_HadiWarningNotificationLog)
    Public Overridable Property tbl_File1 As ICollection(Of tbl_File) = New HashSet(Of tbl_File)
    Public Overridable Property tbl_File2 As tbl_File
    Public Overridable Property tbl_LoanSponsor As ICollection(Of tbl_LoanSponsor) = New HashSet(Of tbl_LoanSponsor)
    Public Overridable Property tbl_HandyFollow As ICollection(Of tbl_HandyFollow) = New HashSet(Of tbl_HandyFollow)
    Public Overridable Property tbl_Loan As ICollection(Of tbl_Loan) = New HashSet(Of tbl_Loan)
    Public Overridable Property tbl_WarningNotificationLog As ICollection(Of tbl_WarningNotificationLog) = New HashSet(Of tbl_WarningNotificationLog)
    Public Overridable Property tbl_Deposits As ICollection(Of tbl_Deposits) = New HashSet(Of tbl_Deposits)

End Class
