'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_HadiOperation_Loan
    Public Property ID As Integer
    Public Property Date_p As Nullable(Of Date)
    Public Property LCProfit As Nullable(Of Decimal)
    Public Property LCAamountPaid As Nullable(Of Decimal)
    Public Property AmountDefferd As Nullable(Of Decimal)
    Public Property Status As String
    Public Property NotPaidDurationDay As Nullable(Of Integer)
    Public Property NoDelayInstallment As Nullable(Of Integer)
    Public Property LCBalance As Nullable(Of Decimal)
    Public Property Amount_MustPay As Nullable(Of Decimal)
    Public Property FK_FileID As Nullable(Of Integer)
    Public Property FK_DepositTypeID As Nullable(Of Integer)
    Public Property NoPaidInstallment As Nullable(Of Integer)
    Public Property Process As Nullable(Of Boolean)
    Public Property FK_BranchID As Nullable(Of Integer)

    Public Overridable Property tbl_HadiOperation_Loan1 As tbl_HadiOperation_Loan
    Public Overridable Property tbl_HadiOperation_Loan2 As tbl_HadiOperation_Loan

End Class
