'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_LoanType
    Public Property ID As Integer
    Public Property LoanTypeCode As String
    Public Property LoanTypeName As String
    Public Property FK_CUserID As Nullable(Of Integer)
    Public Property STime As Nullable(Of Date)
    Public Property Section As String

    Public Overridable Property tbl_Loan As ICollection(Of tbl_Loan) = New HashSet(Of tbl_Loan)
    Public Overridable Property tbl_WarningIntervalsLoanType As ICollection(Of tbl_WarningIntervalsLoanType) = New HashSet(Of tbl_WarningIntervalsLoanType)
    Public Overridable Property tbl_HadiWarningIntervalsLoan As ICollection(Of tbl_HadiWarningIntervalsLoan) = New HashSet(Of tbl_HadiWarningIntervalsLoan)
    Public Overridable Property tbl_HadiOperation_Loan As ICollection(Of tbl_HadiOperation_Loan) = New HashSet(Of tbl_HadiOperation_Loan)

End Class
