'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_HandyFollow
    Public Property ID As Integer
    Public Property FK_FileID As Nullable(Of Integer)
    Public Property FK_LoanID As Nullable(Of Integer)
    Public Property NotificationTypeID As Nullable(Of Integer)
    Public Property ToSponsor As Nullable(Of Boolean)
    Public Property FK_AudienceFileID As Nullable(Of Integer)
    Public Property ContactDate As Nullable(Of Date)
    Public Property FK_UserID As Nullable(Of Integer)
    Public Property STime As Nullable(Of Date)
    Public Property Remarks As String
    Public Property Answered As Nullable(Of Boolean)
    Public Property IsSuccess As Nullable(Of Boolean)
    Public Property DutyDate As Nullable(Of Date)

    Public Overridable Property tbl_File As tbl_File
    Public Overridable Property tbl_Loan As tbl_Loan
    Public Overridable Property tbl_User As tbl_User

End Class
