'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DraftManagement
    
    '''<summary>
    '''Bootstrap_Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Bootstrap_Panel1 As Global.MehrVosul.Bootstrap_Panel
    
    '''<summary>
    '''lblInnerPageTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInnerPageTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''divResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divResult As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''tblResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblResult As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''lnkbtnSMSBorrower control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnSMSBorrower As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkbtnSMSSponsor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnSMSSponsor As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkbtnIntroductionBorrower control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnIntroductionBorrower As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkbtnIntroductionSponsor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnIntroductionSponsor As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkbtnNoticeBorrower control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnNoticeBorrower As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkbtnNoticeSponsor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnNoticeSponsor As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkbtnManifestBorrower control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnManifestBorrower As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkbtnManifestSponsor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnManifestSponsor As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkbtnVoiceMSGBorrower control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnVoiceMSGBorrower As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkbtnVoiceMSGSponsor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnVoiceMSGSponsor As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''hdnAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnAction As Global.System.Web.UI.WebControls.HiddenField
End Class
