'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class StartPage
    
    '''<summary>
    '''divBranchAdminInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divBranchAdminInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''tblSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblSummary As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''lblUserName1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUserName1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblUserRole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUserRole As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPublicNews control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPublicNews As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblProvinceNews control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProvinceNews As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNewFileNotAssign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNewFileNotAssign As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFileAssignNotDone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFileAssignNotDone As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMassiveFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMassiveFile As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDueDateFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDueDateFile As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDueDateFilePeroid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDueDateFilePeroid As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDueDateFileCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDueDateFileCount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDeferredPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeferredPeriod As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDeferredCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeferredCount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDoubtfulPaidPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDoubtfulPaidPeriod As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDoubtfulPaidCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDoubtfulPaidCount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''divUserAdminInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divUserAdminInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Table1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table1 As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''lblNormalUserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNormalUserName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNormalUserRole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNormalUserRole As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNormalPublicNotice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNormalPublicNotice As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNormalProvinceNotice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNormalProvinceNotice As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblAssignedFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAssignedFiles As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDefferedFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDefferedFiles As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''div1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lnkbtnUserManual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnUserManual As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''divLogError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divLogError As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblLogError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLogError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''divLogSuccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divLogSuccess As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblLogSuccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLogSuccess As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''divSMSError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSMSError As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblSMSError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSMSError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''divSMSSuccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSMSSuccess As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblSMSSuccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSMSSuccess As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''divItemAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divItemAdmin As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblItemAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblItemAdmin As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tblLogDetaile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblLogDetaile As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''lblLastDayStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastDayStatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTodayStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTodayStatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblLastDayBI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastDayBI As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTodayBI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTodayBI As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblLastDayFirstSent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastDayFirstSent As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTodayFirstSent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTodayFirstSent As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblLastDayLastSent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastDayLastSent As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTodayLastSent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTodayLastSent As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblLastDaySMSCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastDaySMSCount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTodaySMSCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTodaySMSCount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblLastDaySMSVoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastDaySMSVoice As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTodaySMSVoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTodaySMSVoice As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblLastDayPreSMS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastDayPreSMS As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTodayPreSMS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTodayPreSMS As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBILastDayCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBILastDayCount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBITodayCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBITodayCount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblLastDaySendTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastDaySendTime As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTodaySendTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTodaySendTime As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''divBranchAdmin1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divBranchAdmin1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divchklstAssignFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divchklstAssignFiles As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divBranchAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divBranchAdmin As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divchklstAssignFiles1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divchklstAssignFiles1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divBranchAdmin3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divBranchAdmin3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divBranchAdmin4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divBranchAdmin4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divBranchUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divBranchUser As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divBranchUser1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divBranchUser1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divadmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divadmin As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
